package com.bpkpad.arsipnonkeu.ui.screen.dashboard

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.bpkpad.arsipnonkeu.di.ArchiveModule
import com.bpkpad.arsipnonkeu.domain.model.ArchiveYearSummary
import com.bpkpad.arsipnonkeu.domain.model.ArchiveDocument
import com.bpkpad.arsipnonkeu.domain.model.DocumentStatus
import com.bpkpad.arsipnonkeu.domain.model.DocumentType
import com.bpkpad.arsipnonkeu.domain.model.PhysicalForm
import com.bpkpad.arsipnonkeu.domain.repository.ArchiveRepository
import com.bpkpad.arsipnonkeu.domain.usecase.GetArchiveYearSummariesUseCase
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch


data class ArchiveYearDashboardUiState(
    val isLoading: Boolean = false,
    val years: List<ArchiveYearSummary> = emptyList(),
    val errorMessage: String? = null
)

class DashboardViewModel(
    private val getArchiveYearSummariesUseCase: GetArchiveYearSummariesUseCase =
        ArchiveModule.getArchiveYearSummariesUseCase,
    private val archiveRepository: ArchiveRepository =
        ArchiveModule.archiveRepositoryInstance
) : ViewModel(){
    private val _uiState = MutableStateFlow(ArchiveYearDashboardUiState())
    val uiState: StateFlow<ArchiveYearDashboardUiState> = _uiState.asStateFlow()

    fun loadYears() {
        viewModelScope.launch {
            _uiState.value = _uiState.value.copy(
                isLoading = true,
                errorMessage = null
            )

            try {
                val years = getArchiveYearSummariesUseCase()

                _uiState.value = _uiState.value.copy(
                    isLoading = false,
                    years = years
                )
            } catch (exception: Exception) {
                _uiState.value = _uiState.value.copy(
                    isLoading = false,
                    errorMessage = exception.message ?: "Gagal memuat data tahun arsip"
                )
            }
        }
    }

    fun addNewYear(year: Int) {
        viewModelScope.launch {
            _uiState.value = _uiState.value.copy(isLoading = true)
            try {
                // Check if year already exists
                if (_uiState.value.years.any { it.year == year }) {
                    throw Exception("Tahun $year sudah ada.")
                }

                // Create a placeholder document to make the year appear in the list
                val placeholder = ArchiveDocument(
                    id = "", // Will be generated by repository
                    documentType = DocumentType.SURAT,
                    documentNumber = null,
                    classificationCode = null,
                    title = "Placeholder $year",
                    description = "Dokumen pembuka untuk tahun $year. Silakan hapus jika sudah ada dokumen lain.",
                    year = year,
                    physicalForm = PhysicalForm.SHEET,
                    condition = null,
                    copyCount = 1,
                    isCopy = null,
                    status = DocumentStatus.AVAILABLE,
                    originInstance = null,
                    createdBy = null,
                    updatedBy = null,
                    createdAt = null,
                    updatedAt = null,
                    deletedAt = null // Soft deleted so it doesn't show in the list but counts for year
                )

                archiveRepository.createArchiveDocument(placeholder)
                
                // Refresh the list
                loadYears()
            } catch (exception: Exception) {
                _uiState.value = _uiState.value.copy(
                    isLoading = false,
                    errorMessage = exception.message ?: "Gagal menambah tahun baru"
                )
            }
        }
    }
}
